[workspace]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "gpu-intro"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
mojo = ">=0.25.7.0.dev2025101305,<0.26"
